#ifndef LINEFOLLOWDEFINES_H
#define LINEFOLLOWDEFINES_H

#define FOLLOW_STATE_START 0x0
#define FOLLOW_STATE_CHECK 0x1
#define FOLLOW_STATE_PID   0x2
#define FOLLOW_STATE_MOTOR 0x3
#define FOLLOW_STATE_STOP  0x4

#define FOLLOW_PID_P 1/20
#define FOLLOW_PID_D 3/2
#define FOLLOW_PID_I 1/10000
#define FOLLOW_MAX_SPEED 100.0

#define DEV_ID 0x2A
#define PARANCS_LEKERDEZES_ID 0xB0

#define MAX_UART_TRY 5

#define FOLLOW_INTERSECTION_LIMIT 3

#define FOLLOW_STATE_FOLLOW_RUNNING 0
#define FOLLOW_STATE_DISTANCE_STOP 1
#define FOLLOW_STATE_INTERSECTION_STOP 2
#define FOLLOW_STATE_OTHER_STOP 3

#define FOLLOW_LINE_TURN_CONST 0.5
#define FOLLOW_LINE_TURN_SPEED 1
#define FOLLOW_LINE_TURN_ACCEL 1

#define FOLLOW_LINE_GO_DIST 40
#define FOLLOW_LINE_GO_SPEED 10
#define FOLLOW_LINE_GO_ACCEL 10

#define FOLLOW_PERIOD_US 1000

#endif
